# ArgoCD will error if you attempt to render a chart that generates no manifests
# The only way I can think of to get around this is to put out a dummy resource
# while ibm_mas_suite_app_install is unset (and so none of the other templates in this chart are being rendered)
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Values.stub_id }}-{{ .Values.account_id }}-{{ .Values.region_id }}-{{ .Values.cluster_id }}"
  namespace: {{ .Values.mas_app_namespace }}
data:
  this-is-just-a-placeholder-resource: ""
