---
apiVersion: batch/v1
kind: Job
metadata:
  name: "postdelete-{{ .Values.stub_id }}-{{ .Values.account_id }}-{{ .Values.region_id }}-{{ .Values.cluster_id }}"
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostDelete
spec:
  template:
    spec:
      containers:
        - name: run
          # TODO: use a dedicated image with a smaller footprint for this sort of thing?
          # Just using cli for now since it has all the deps we need to talk with AWS SM
          image: quay.io/ibmmas/cli:8.1.0-pre.gitops
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
          env:
          volumeMounts: []
          command:
            - /bin/sh
            - -c
            - |

              echo "done"


      restartPolicy: Never
      serviceAccountName: default
      volumes: []
  backoffLimit: 4