{{- if not (empty .Values.stub2) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stub2.{{.Values.account.id}}.{{.Values.region.id}}.{{ .Values.cluster.id }}.{{ .Values.instance.id }}
  namespace: {{ .Values.argo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    {{- if and .Values.notifications .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-failed.workspace1: {{ .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-succeeded.workspace1: {{ .Values.notifications.slack_channel_id }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: '*'
    kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
  project: "{{ .Values.argo.projects.apps }}"
  destination:
    server: {{ .Values.cluster.url }}
    namespace: default
  source:
    repoURL: "{{ .Values.source.repo_url }}"
    path: applications/stub
    targetRevision: "{{ .Values.source.revision }}"
    plugin:
      name: {{ .Values.avp.name }} 
      env:
        - name: {{ .Values.avp.values_varname }}
          value: |
            account_id: "{{ .Values.account.id }}"
            region_id: "{{ .Values.region.id }}"
            cluster_id: "{{ .Values.cluster.id }}"
            stub_id: "{{ .Values.instance.id }}-2"
        - name: ARGOCD_APP_NAME
          value: syncres
        {{- if not (empty .Values.avp.secret) }}
        - name: AVP_SECRET
          value: {{ .Values.avp.secret }}
        {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
{{- end }}